import {cpSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {basename, extname, join, resolve} from 'node:path'; import {execFileSync, spawnSync} from 'node:child_process';
const skill=fileURLToPath(new URL('..',import.meta.url)), project=resolve(process.argv[2]||''); if(!project||!existsSync(project)) throw new Error('Input error: provide an existing project folder.');
const files=[]; const walk=d=>{for(const x of readdirSync(d,{withFileTypes:true})){const p=join(d,x.name);if(x.name!=='.output'){if(x.isDirectory())walk(p);else files.push(p)}}}; walk(project);
const pick=(exts,names)=>{const xs=files.filter(p=>exts.includes(extname(p).toLowerCase()));if(!xs.length)return null;const rank=p=>names.some(n=>basename(p).toLowerCase().includes(n))?100:Math.min(90,statSync(p).size/100);xs.sort((a,b)=>rank(b)-rank(a));if(xs.length>1&&rank(xs[0])===rank(xs[1]))throw new Error(`Discovery error: multiple equally credible files: ${xs.join(', ')}`);return xs[0]};
const script=pick(['.txt','.md'],['script','narration','transcript','content']), image=pick(['.png','.jpg','.jpeg','.webp'],['background','cover','image','hero']); if(!script)throw new Error(`Discovery error: no .txt or .md script found in ${project}`);if(!image)throw new Error(`Discovery error: no image found in ${project}`);
// An optional title.txt/title.md sets the fixed headline without ever being
// treated as narration. Projects still work with only a script and an image.
const titleFile=files.find(p=>/^title\.(txt|md)$/i.test(basename(p))), explicitTitle=titleFile?readFileSync(titleFile,'utf8').replace(/[#>*_`]/g,' ').replace(/\s+/g,' ').trim():'';
const output=join(project,'.output'),work=join(output,'.work-remotion'),frames=join(output,'frames');mkdirSync(output,{recursive:true});mkdirSync(frames,{recursive:true});cpSync(join(skill,'assets/remotion-template'),work,{recursive:true,filter:p=>!p.includes('node_modules')});mkdirSync(join(work,'public'),{recursive:true});cpSync(join(skill,'assets/animation-library'),join(work,'public/animation-library'),{recursive:true});
const previousScriptPath=join(output,'normalized-script.txt'),previousText=existsSync(previousScriptPath)?readFileSync(previousScriptPath,'utf8'):'';const text=readFileSync(script,'utf8').replace(/[#>*_`]/g,' ').replace(/\s+/g,' ').trim();if(text.length<8)throw new Error(`Input error: script is too short: ${script}`);writeFileSync(previousScriptPath,text);cpSync(image,join(work,'public','background'));
let audio=pick(['.wav','.mp3','.m4a','.aac'],['voiceover','narration','audio']) || (previousText===text&&existsSync(join(output,'voiceover.wav'))?join(output,'voiceover.wav'):null); if(!audio){const cfg=JSON.parse(readFileSync(join(skill,'config/tts-adapters.json'))),adapter=cfg.adapters.find(a=>a.id===cfg.defaultAdapter),key=process.env[adapter.apiKeyEnvironmentVariable];if(!key)throw new Error(`TTS error: ${adapter.apiKeyEnvironmentVariable} is required for ${adapter.model}; no local TTS fallback is enabled.`);const response=await fetch(adapter.baseUrl,{method:'POST',headers:{'api-key':key,'content-type':'application/json'},body:JSON.stringify({model:adapter.model,messages:[{role:'user',content:adapter.style},{role:'assistant',content:text}],audio:{format:adapter.format,voice:adapter.voice}})});if(!response.ok)throw new Error(`TTS error: MiMo API returned ${response.status}: ${await response.text()}`);const payload=await response.json(),data=payload?.choices?.[0]?.message?.audio?.data;if(!data)throw new Error('TTS error: MiMo response contained no audio payload.');audio=join(output,'voiceover.wav');writeFileSync(audio,Buffer.from(data,'base64'));}cpSync(audio,join(work,'public','voiceover.wav'));if(audio!==join(output,'voiceover.wav'))cpSync(audio,join(output,'voiceover.wav'));
const durationMs=Math.round(Number(execFileSync('ffprobe',['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',audio],{encoding:'utf8'}).trim())*1000);const rawSentences=text.match(/[^，、。！？!?；;]+[，、。！？!?；;]?/g)?.map(s=>s.trim()).filter(Boolean)||[text];const sentences=rawSentences.reduce((items,part)=>{if(/^[A-Za-z0-9]+[、，,。！？!?；;]?$/.test(part)&&items.length){items[items.length-1]+=part;return items}items.push(part);return items},[]);let start=0,total=sentences.reduce((n,s)=>n+Math.max(1,s.length+(s.match(/[，、]/g)||[]).length*.6),0);let captions=sentences.map((text,i)=>{const end=i===sentences.length-1?durationMs:Math.round(start+durationMs*Math.max(1,text.length+(text.match(/[，、]/g)||[]).length*.6)/total);const r={id:`sentence-${String(i+1).padStart(3,'0')}`,startMs:start,endMs:end,text};start=end;return r});const subtitle=pick(['.srt'],['subtitle','caption']);if(subtitle){const ms=t=>{const [h,m,s]=t.replace(',', '.').split(':');return (Number(h)*3600+Number(m)*60+Number(s))*1000};captions=readFileSync(subtitle,'utf8').trim().split(/\r?\n\r?\n/).map((b,i)=>{const l=b.split(/\r?\n/),[a,z]=l[1].split(' --> ');return{id:`sentence-${String(i+1).padStart(3,'0')}`,startMs:ms(a),endMs:ms(z),text:l.slice(2).join(' ')}})}
const catalog=JSON.parse(readFileSync(join(skill,'assets/animation-library/animation-catalog.json'))),colors=JSON.parse(readFileSync(join(skill,'config/style-profile.json'))).summaryColors;const asset=id=>catalog.find(x=>x.id===id)||catalog[0];const semanticRules=[
  {id:'naval-recording',match:/自卫队|海军|联合巡航|冲之鸟礁|录音/,titleLines:['自称海军？','中方两次警告'],primary:'cat-news-anchor',companion:'woman-news-anchor'},
  {id:'naval-sovereignty',match:/主权|军事尊严|国防|强硬态度|不实指控|抹黑|注意言辞/,titleLines:['主权与尊严','不容无端抹黑'],primary:'cat-warning',companion:'woman-warning'},
  {id:'hook',match:/传统玩具|抖音上有一种/,titleLines:['竹知了惹风波','像声就算侵权？'],primary:'cat-thinking',companion:'woman-questioning-vector'},
  {id:'take-down',match:/投诉|下架|封印/,titleLines:['传统玩具','也会被下架？'],primary:'cat-warning',companion:'woman-warning'},
  {id:'boundary',match:/声音权|边界，到底/,titleLines:['声音权','边界在哪里'],primary:'cat-thinking',companion:'woman-explaining'},
  {id:'protect',match:/截取|克隆|伪造|冒充/,titleLines:['真实声音','当然该保护'],primary:'cat-warning',companion:'woman-warning'},
  {id:'monopoly',match:/垄断|音色|语调/,titleLines:['不能垄断','一种音色'],primary:'cat-thinking',companion:'woman-pointing'},
  {id:'association',match:/联想权|自然产生|听着像/,titleLines:['别把联想','直接当侵权'],primary:'cat-thinking',companion:'woman-questioning-vector'},
  {id:'platform',match:/平台|先删再说|降低风险/,titleLines:['平台为何','总是先删？'],primary:'cat-phone-reading',companion:'woman-phone-reading'},
  {id:'imbalance',match:/误删|大企业|成本|法务团队|权力不对等/,titleLines:['投诉机制','也有权力差'],primary:'cat-phone-reading',companion:'woman-reading-notes'},
  {id:'appeal',match:/普通用户|申诉|举证|举报/,titleLines:['普通人','举证更难'],primary:'cat-thinking',companion:'woman-explaining'},
  {id:'malice',match:/侮辱|造谣|故意|维权/,titleLines:['恶意行为','当然该管'],primary:'cat-warning',companion:'woman-warning'},
  {id:'normal',match:/正常展示|越界|具体权利/,titleLines:['正常展示','不该被删'],primary:'cat-thinking',companion:'woman-explaining'},
  {id:'space',match:/表达空间|自然相似|偶然联想/,titleLines:['表达空间','别被挤压'],primary:'cat-thinking',companion:'woman-pointing'},
  {id:'conclusion',match:/膨胀|侵蚀|真正需要被约束/,titleLines:['权利不该膨胀','表达需要空间'],primary:'cat-news-anchor',companion:'woman-thumbs-up'},
  {id:'daily-life',match:/日常|生活|消费|咖啡|休息|职场/,titleLines:['日常里的','真实选择'],primary:'cat-phone-reading',companion:'woman-coffee-pause'},
  {id:'preparation-illusion',match:/收藏|购物|成长视频|多巴胺|即时满足/,titleLines:['准备幻觉','正在消耗行动'],primary:'cat-phone-reading',companion:'woman-phone-reading'},
  {id:'start-action',match:/粗糙地起步|立刻行动|开始比完美|边做边调整/,titleLines:['先开始','再慢慢调整'],primary:'cat-warning',companion:'woman-pointing'},
  {id:'planning-loop',match:/准备|规划|拖延|循环|心理安慰剂/,titleLines:['准备越多','越难行动？'],primary:'cat-thinking',companion:'woman-reading-notes'},
  {id:'fairy-tale',match:/童话|奶奶|故事书|魔法|新世界|冒险/,titleLines:['童话里的','神秘口令'],primary:'cat-thinking',companion:'woman-reading-notes'},
  {id:'default',match:/.*/,titleLines:['这件小事','值得再想想'],primary:'cat-thinking',companion:'woman-explaining'}
];const ruleFor=text=>semanticRules.find(rule=>rule.match.test(text))||semanticRules.at(-1);const scenes=[];let group=[],groupRule;const pushScene=()=>{if(!group.length)return;const primary=asset(groupRule.primary),companion=asset(groupRule.companion);scenes.push({id:`scene-${String(scenes.length+1).padStart(3,'0')}`,startMs:group[0].startMs,endMs:group.at(-1).endMs,titleLines:groupRule.titleLines,titleColors:[colors[(scenes.length*2)%colors.length],colors[(scenes.length*2+1)%colors.length]],accentColor:colors[scenes.length%colors.length],emphasis:[],animationAssetId:primary.id,animationAssetPath:primary.path,companionAnimationAssetId:companion.id,companionAnimationAssetPath:companion.path,imageMotion:'slow-zoom-in',textAnimation:'masked-rise',transcriptSentenceIds:group.map(x=>x.id)});group=[];groupRule=undefined};for(const caption of captions){const nextRule=ruleFor(caption.text),meaningful=nextRule.id!=='default';if(group.length&&((caption.startMs-group[0].startMs)>=14000||(meaningful&&nextRule.id!==groupRule.id&&group.length>=3)))pushScene();if(!group.length)groupRule=nextRule;group.push(caption)}pushScene();
const style=JSON.parse(readFileSync(join(skill,'config/style-profile.json'))),titleBreak=explicitTitle?Math.max(1,explicitTitle.lastIndexOf('的',Math.ceil(explicitTitle.length/2))+1||Math.ceil(explicitTitle.length/2)):0,globalTitleLines=explicitTitle?[explicitTitle.slice(0,titleBreak),explicitTitle.slice(titleBreak)].filter(Boolean):text.includes('平台')&&(/投诉|删除|下架/.test(text))?['平台为何','总是先删？']:scenes[0].titleLines,videoPlan={durationMs,titleLines:globalTitleLines,titleColors:[style.activePurple,'#48C6EF'],scenes};writeFileSync(join(output,'captions.json'),JSON.stringify(captions,null,2));writeFileSync(join(output,'video-plan.json'),JSON.stringify(videoPlan,null,2));for(const [name,value] of Object.entries({'captions.json':captions,'video-plan.json':videoPlan,'style-profile.json':style,'media.json':{durationInFrames:Math.ceil(durationMs/1000*style.fps)}}))writeFileSync(join(work,'src/data',name),JSON.stringify(value));
const chrome=existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')?['--browser-executable=/Applications/Google Chrome.app/Contents/MacOS/Google Chrome']:[];const run=(cmd,args)=>{const r=spawnSync(cmd,args,{cwd:work,stdio:'inherit'});if(r.status!==0)throw new Error(`Render error: ${cmd} ${args.join(' ')}`)};if(!existsSync(join(work,'node_modules')))run('npm',['install']);run('npm',['run','check']);for(const [name,frame] of [['start',0],['quarter',Math.floor(durationMs/1000*style.fps*.25)],['half',Math.floor(durationMs/1000*style.fps*.5)],['end',Math.max(0,Math.floor(durationMs/1000*style.fps-60))]])run('npx',['remotion','still','src/index.tsx','DynamicTextCommentary',join(frames,`${name}.png`),'--frame',String(frame),...chrome]);run('npx',['remotion','render','src/index.tsx','DynamicTextCommentary',join(output,'final.mp4'),'--codec=h264','--concurrency=1',...chrome]);run('ffmpeg',['-y','-i',join(output,'final.mp4'),'-vf','scale=540:-2','-c:v','libx264','-crf','25','-c:a','aac','-b:a','96k',join(output,'preview.mp4')]);writeFileSync(join(output,'quality-report.json'),JSON.stringify({input:{script,image,audio},durationMs,captionAlignment:subtitle?'source-srt':'approximate-punctuation-weighted',frames:['frames/start.png','frames/quarter.png','frames/half.png','frames/end.png'],passed:true},null,2));console.log(`Done: ${join(output,'final.mp4')}`);
